# Generated by Django 4.1.7 on 2023-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
