# Generated by Django 4.1.7 on 2023-06-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
