# Generated by Django 4.1.7 on 2023-06-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
