# Generated by Django 4.1.7 on 2023-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_rename_flight_id_flight_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
