# Generated by Django 4.1.7 on 2023-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_flight_flight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='from_loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
